Add coming soon logic into course page. Add offer agreement.
nikolas77380/codeway.online pull request #130
Opened 2024-11-14 16:04 UTC by cepuii

2024-11-17 16:17 UTC, nikolas77380 commented on src/components/CoursePage/MainBlock/CardInfo/ActionButton.tsx
> +  if (course.id === "tviy-mentor") {
Это можно упростить если условие создать только для сообщения и текста кнопки

2024-11-21 08:50 UTC, nikolas77380 requested changes

2024-11-21 08:50 UTC, nikolas77380 commented on src/components/contactUs/form/ContactUsForm.tsx
>    const [contactMethod, setContactMethod] = useState("telegram");
add type please : type ContactMethodType = "telegram" | 'text' | 'email' 
useState<ContactMethodType>("telegram")

2024-11-21 13:58 UTC, cepuii commented on src/components/contactUs/form/ContactUsForm.tsx
>    const [contactMethod, setContactMethod] = useState("telegram");
done [commit link](https://github.com/nikolas77380/codeway.online/pull/130/commits/18d9b2f06946ce416c49a919911432d45f1035c9)

2024-11-22 08:49 UTC, nikolas77380 approved these changes

2024-11-22 08:50 UTC, merged